version: '3.3'

services:

  db:
    env_file:
      - .env
    image: postgres:13.0-alpine

    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
       - postgres_data:/var/lib/postgresql/data/
    restart: always

  backend:
    image: maksimarzamastsev/foodgram-backend:latest
    restart: always
    depends_on:
      - db
    volumes:
      - static_value:/app/backend/staticfiles/
      - media_value:/app/backend/media/
    env_file:
      - ./.env

  frontend:
    image: maksimarzamastsev/foodgram-frontend:latest
    volumes:
      - result_build:/app/result_build/build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - result_build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    restart: always
    depends_on:
      - backend


volumes:
  result_build:
  postgres_data:
  static_value:
  media_value:
